# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20160322_1157'),
        ('projects', '0035_merge'),
    ]

    operations = [
    ]
