# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_attributes', '0007_auto_20160208_1751'),
        ('custom_attributes', '0007_auto_20160112_0859'),
    ]

    operations = [
    ]
